FROM node:8.9

# create working dir
RUN mkdir -p /var/app
WORKDIR /var/app

# copy app to dir
COPY . /var/app

# set environment variables
ENV NODE_PATH=./lib NODE_ENV=production

# install npm modules
RUN npm install --production

# expose ports
EXPOSE 3000

# run the app
CMD ["node", "web/bin/www"]
