FROM node:8.9

# create working dir
RUN mkdir -p /var/app
WORKDIR /var/app

# install npm modules for production
COPY package.json /var/app
RUN npm install

# copy app to dir
COPY . /var/app

# set development environment
ENV NODE_ENV=development

# cache the npm modules and improve performance
VOLUME /var/app/node_modules

# expose ports
EXPOSE 3000 4001
